### ISSUE TITLE
Implementing the codes to the new site

### ISSUE THREAD

**Issue by EmineSener** [btu-cse/telegrot#16]

**Comment by fatiiates** [comment]
Hey @EmineSener, glad to see you here!

As you know we have a scraping method that left from older codebase. And we need to update this method because our website is totally renewed and moved to another domain.

# Resources

## The method
Method is in this file [Replica bot](https://github.com/btu-cse/telegrot/blob/master/src/bot_replica/replica_class.py#L35)

```python

    # sends new announcements to the telegram chats: developed for the announcing to students/teachers/everybody about news
    def send_announcements_to_chats(self, context):

```

## The website

Here is the new domain: http://mdbf.btu.edu.tr/bilgisayar 

# What to do?

So, what should you do to fix this issue?

- Clone our master branch to your local and make a new branch.
- Update the scraping method completely
- When you have done, create a PR

If you have questions, don't be shy.
